"""
scoring_service.py — Deterministic sector and company scoring engine.

Scores are computed from real data in the database — NOT generated by the LLM.
The LLM receives pre-computed scores as facts and only explains/contextualises them.

Score scale: 1 (very low) → 5 (very high)
"""
from __future__ import annotations

import logging
import re
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from sqlalchemy.orm import Session

log = logging.getLogger(__name__)

# ── Keyword dictionaries ──────────────────────────────────────────────────────

_AI_KEYWORDS = [
    "artificial intelligence", "machine learning", "deep learning", "neural network",
    "computer vision", "natural language", "nlp", "llm", "generative ai",
    "foundation model", "ai-powered", "ai-native", "ai platform", "ml model",
    "predictive", "automation", "intelligent", "algorithm", "data-driven",
]

_DEFENSIBILITY_KEYWORDS = [
    "proprietary", "patent", "patented", "ip", "intellectual property",
    "data moat", "exclusive data", "unique dataset", "network effect",
    "switching cost", "lock-in", "regulatory approval", "fda", "ce mark",
    "first mover", "barrier to entry", "trade secret",
]

_COMMERCIAL_KEYWORDS = [
    "revenue", "arr", "mrr", "customer", "client", "enterprise", "contract",
    "deployed", "live", "production", "paying", "growth", "scale", "expansion",
    "series a", "series b", "series c", "profitable",
]

_EARLY_STAGE_KEYWORDS = ["seed", "pre-seed", "mvp", "prototype", "pilot", "pre-revenue"]
_GROWTH_STAGE_KEYWORDS = ["series a", "series b", "series c", "growth", "scale", "profitable"]


def _keyword_score(text: str, keywords: list[str], max_hits: int = 5) -> float:
    """Return 1–5 based on keyword hit count in text."""
    text_lower = text.lower()
    hits = sum(1 for kw in keywords if kw in text_lower)
    return min(5.0, 1.0 + (hits / max_hits) * 4.0)


def _clamp(value: float) -> float:
    return round(max(1.0, min(5.0, value)), 1)


# ── Sector scoring ────────────────────────────────────────────────────────────

def score_sector(sector_name: str, db: "Session") -> dict | None:
    """
    Compute deterministic scores for a sector based on Merantix's actual data.
    Returns a dict with scores + evidence, or None if no data found.
    """
    from sqlalchemy import func, select
    from ..models import CrmVenture, KnowledgeChunk

    sector_lower = sector_name.lower()

    # Fetch all ventures in this sector
    ventures = db.scalars(
        select(CrmVenture)
        .where(CrmVenture.name.is_not(None))
        .where(func.lower(CrmVenture.sector).contains(sector_lower))
    ).all()

    if not ventures:
        # Try broader match
        ventures = db.scalars(
            select(CrmVenture)
            .where(CrmVenture.name.is_not(None))
            .where(CrmVenture.description.ilike(f"%{sector_lower}%"))
        ).all()

    if not ventures:
        return None

    portfolio = [v for v in ventures if "portfolio" in (v.stage or "").lower()]
    pipeline = [v for v in ventures if v not in portfolio]
    total = len(ventures)

    # ── 1. Market Opportunity ─────────────────────────────────────────────────
    # Based on portfolio depth + pipeline activity
    portfolio_count = len(portfolio)
    pipeline_count = len(pipeline)
    market_raw = 1.0
    if portfolio_count >= 5:    market_raw = 5.0
    elif portfolio_count >= 3:  market_raw = 4.0
    elif portfolio_count >= 2:  market_raw = 3.5
    elif portfolio_count >= 1:  market_raw = 3.0
    else:                       market_raw = 2.0
    # Pipeline activity boosts the score
    market_raw = min(5.0, market_raw + (pipeline_count * 0.15))
    market_score = _clamp(market_raw)
    market_evidence = (
        f"{portfolio_count} portfolio {'company' if portfolio_count == 1 else 'companies'}"
        + (f", {pipeline_count} in active pipeline evaluation" if pipeline_count else "")
    )

    # ── 2. AI Readiness ───────────────────────────────────────────────────────
    # Based on AI keyword density across all company descriptions + notes
    all_text = " ".join(
        (v.description or "") + " " + (v.name or "")
        for v in ventures
    )
    # Also pull knowledge chunk text for this sector
    chunk_rows = db.execute(
        select(KnowledgeChunk.text)
        .where(KnowledgeChunk.crm_venture_id.in_([v.id for v in ventures]))
        .where(KnowledgeChunk.text.is_not(None))
        .limit(50)
    ).scalars().all()
    all_text += " " + " ".join(c or "" for c in chunk_rows)

    ai_score = _clamp(_keyword_score(all_text, _AI_KEYWORDS, max_hits=8))
    ai_hits = [kw for kw in _AI_KEYWORDS if kw in all_text.lower()][:5]
    ai_evidence = f"AI signals detected: {', '.join(ai_hits) if ai_hits else 'limited'} across {total} companies"

    # ── 3. Commercial Maturity ────────────────────────────────────────────────
    # Based on stage distribution and commercial signals in descriptions
    growth_count = sum(
        1 for v in ventures
        if any(kw in (v.stage or "").lower() + (v.description or "").lower()
               for kw in _GROWTH_STAGE_KEYWORDS)
    )
    commercial_score_raw = _keyword_score(all_text, _COMMERCIAL_KEYWORDS, max_hits=6)
    # Weight by portfolio companies at growth stage
    if portfolio_count > 0:
        growth_ratio = growth_count / max(1, portfolio_count)
        commercial_score_raw = (commercial_score_raw + 1 + growth_ratio * 2) / 2
    commercial_score = _clamp(commercial_score_raw)
    commercial_evidence = (
        f"{growth_count} companies show growth-stage signals"
        + (f" out of {portfolio_count} portfolio" if portfolio_count else "")
    )

    # ── 4. Defensibility ─────────────────────────────────────────────────────
    # Based on IP/moat keywords in notes and descriptions
    defensibility_score = _clamp(_keyword_score(all_text, _DEFENSIBILITY_KEYWORDS, max_hits=5))
    def_hits = [kw for kw in _DEFENSIBILITY_KEYWORDS if kw in all_text.lower()][:4]
    defensibility_evidence = (
        f"Moat signals: {', '.join(def_hits)}" if def_hits
        else "Limited proprietary/IP signals found in available data"
    )

    # ── 5. Investment Attractiveness (composite) ──────────────────────────────
    attractiveness_score = _clamp(
        (market_score * 0.30) +
        (ai_score * 0.25) +
        (commercial_score * 0.25) +
        (defensibility_score * 0.20)
    )
    attractiveness_evidence = (
        f"Weighted composite: Market({market_score}×0.30) + "
        f"AI({ai_score}×0.25) + Commercial({commercial_score}×0.25) + "
        f"Defensibility({defensibility_score}×0.20)"
    )

    return {
        "sector": sector_name,
        "total_companies": total,
        "portfolio_companies": portfolio_count,
        "pipeline_companies": pipeline_count,
        "portfolio_names": [v.name for v in portfolio],
        "scores": {
            "market_opportunity":       {"score": market_score,        "evidence": market_evidence},
            "ai_readiness":             {"score": ai_score,            "evidence": ai_evidence},
            "commercial_maturity":      {"score": commercial_score,    "evidence": commercial_evidence},
            "defensibility":            {"score": defensibility_score, "evidence": defensibility_evidence},
            "investment_attractiveness": {"score": attractiveness_score, "evidence": attractiveness_evidence},
        },
        "computed_at": datetime.utcnow().isoformat(),
    }


# ── Company scoring ───────────────────────────────────────────────────────────

def score_company(company_name: str, db: "Session") -> dict | None:
    """
    Compute deterministic scores for a single company.
    """
    from sqlalchemy import select
    from ..models import CrmVenture, KnowledgeChunk

    # Find the company (support aliases via partial match)
    venture = db.scalar(
        select(CrmVenture)
        .where(CrmVenture.name.ilike(f"%{company_name}%"))
        .limit(1)
    )
    if not venture:
        return None

    # Gather all text for this company
    chunks = db.scalars(
        select(KnowledgeChunk)
        .where(KnowledgeChunk.crm_venture_id == venture.id)
        .limit(30)
    ).all()
    all_text = (venture.description or "") + " " + " ".join(c.text or "" for c in chunks)

    # ── AI Capability ─────────────────────────────────────────────────────────
    ai_score = _clamp(_keyword_score(all_text, _AI_KEYWORDS, max_hits=6))
    ai_hits = [kw for kw in _AI_KEYWORDS if kw in all_text.lower()][:4]
    ai_evidence = f"AI signals: {', '.join(ai_hits) if ai_hits else 'limited'}"

    # ── Commercial Traction ───────────────────────────────────────────────────
    commercial_score = _clamp(_keyword_score(all_text, _COMMERCIAL_KEYWORDS, max_hits=5))
    stage = (venture.stage or "").lower()
    if any(kw in stage for kw in _GROWTH_STAGE_KEYWORDS):
        commercial_score = _clamp(commercial_score + 1)
    elif any(kw in stage for kw in _EARLY_STAGE_KEYWORDS):
        commercial_score = _clamp(commercial_score - 0.5)
    commercial_evidence = f"Stage: {venture.stage or 'unknown'} | Commercial signals in data"

    # ── Defensibility ─────────────────────────────────────────────────────────
    defensibility_score = _clamp(_keyword_score(all_text, _DEFENSIBILITY_KEYWORDS, max_hits=4))
    def_hits = [kw for kw in _DEFENSIBILITY_KEYWORDS if kw in all_text.lower()][:3]
    defensibility_evidence = f"Moat signals: {', '.join(def_hits) if def_hits else 'not found in available data'}"

    # ── Data Richness (how much Merantix knows about this company) ────────────
    data_score = _clamp(1.0 + len(chunks) * 0.3)
    data_evidence = f"{len(chunks)} knowledge chunks indexed for this company"

    # ── Merantix Fit (composite) ──────────────────────────────────────────────
    fit_score = _clamp(
        (ai_score * 0.35) +
        (commercial_score * 0.30) +
        (defensibility_score * 0.35)
    )

    return {
        "company": venture.name,
        "sector": venture.sector,
        "stage": venture.stage,
        "scores": {
            "ai_capability":     {"score": ai_score,            "evidence": ai_evidence},
            "commercial_traction": {"score": commercial_score,  "evidence": commercial_evidence},
            "defensibility":     {"score": defensibility_score, "evidence": defensibility_evidence},
            "data_coverage":     {"score": data_score,          "evidence": data_evidence},
            "merantix_fit":      {"score": fit_score,            "evidence": "Weighted composite (AI×0.35 + Commercial×0.30 + Defensibility×0.35)"},
        },
        "computed_at": datetime.utcnow().isoformat(),
    }


# ── Context formatter ─────────────────────────────────────────────────────────

def format_scores_for_context(scored: dict) -> str:
    """Format computed scores into a structured context block for the LLM."""
    if not scored:
        return ""

    lines = [
        "╔══════════════════════════════════════════════════════════════╗",
        "║  COMPUTED SCORES — Based on Merantix's actual database data  ║",
        "║  Use these scores exactly. Do NOT modify or re-estimate.     ║",
        "╚══════════════════════════════════════════════════════════════╝",
        f"Computed at: {scored['computed_at']} UTC",
        "",
    ]

    if "sector" in scored:
        lines.append(f"Sector: {scored['sector']}")
        lines.append(f"Data: {scored['portfolio_companies']} portfolio companies, {scored['pipeline_companies']} in pipeline")
        if scored.get("portfolio_names"):
            lines.append(f"Portfolio: {', '.join(scored['portfolio_names'])}")
    elif "company" in scored:
        lines.append(f"Company: {scored['company']} | Sector: {scored.get('sector', 'N/A')} | Stage: {scored.get('stage', 'N/A')}")

    lines.append("")
    lines.append("SCORES (1=Very Low, 2=Low, 3=Moderate, 4=High, 5=Very High):")

    for criterion, data in scored["scores"].items():
        label = criterion.replace("_", " ").title()
        score = data["score"]
        evidence = data["evidence"]
        bar = "█" * int(score) + "░" * (5 - int(score))
        lines.append(f"  {label:30} {score}/5  [{bar}]")
        lines.append(f"    Evidence: {evidence}")

    lines.append("")
    lines.append("END COMPUTED SCORES")
    return "\n".join(lines)


# ── Query detection ───────────────────────────────────────────────────────────

_SECTOR_TRIGGERS = re.compile(
    r"\b(analys[ei]s|analyse|evaluate|evaluation|thesis|landscape|sector|industry|"
    r"space|market|opportunity|investment case|tell me about|overview|deep.?dive|"
    r"how is|what.?s happening|trend|benchmark|compare sector)\b",
    re.IGNORECASE,
)

_COMPANY_TRIGGERS = re.compile(
    r"\b(evaluate|assessment|analyse|analyze|score|rate|investment case|"
    r"fit for merantix|should merantix|potential investment|due diligence|"
    r"how strong|how good|what do you think of|is .+ a good)\b",
    re.IGNORECASE,
)


def detect_and_score(query: str, focus_company: str | None, db: "Session") -> str:
    """
    Detect if the query warrants scoring, compute scores, return formatted context.
    Returns empty string if scoring is not applicable.
    """
    # Company evaluation query
    if focus_company and _COMPANY_TRIGGERS.search(query):
        try:
            scored = score_company(focus_company, db)
            if scored:
                log.info("Scoring: company evaluation for '%s'", focus_company)
                return format_scores_for_context(scored)
        except Exception as exc:
            log.warning("Company scoring failed for '%s': %s", focus_company, exc)

    # Sector analysis query — extract sector name from query
    if _SECTOR_TRIGGERS.search(query):
        # Try to match a sector from the DB
        from sqlalchemy import select, func
        from ..models import CrmVenture
        sectors = db.execute(
            select(CrmVenture.sector)
            .where(CrmVenture.sector.is_not(None))
            .distinct()
        ).scalars().all()

        query_lower = query.lower()
        matched_sector = None
        for sector in sectors:
            if sector and sector.lower() in query_lower:
                matched_sector = sector
                break

        # Fallback: partial match
        if not matched_sector:
            for sector in sectors:
                if sector:
                    words = sector.lower().split()
                    if any(w in query_lower for w in words if len(w) > 4):
                        matched_sector = sector
                        break

        if matched_sector:
            try:
                scored = score_sector(matched_sector, db)
                if scored:
                    log.info("Scoring: sector analysis for '%s'", matched_sector)
                    return format_scores_for_context(scored)
            except Exception as exc:
                log.warning("Sector scoring failed for '%s': %s", matched_sector, exc)

    return ""
